import frappe

# ─────────────────────────────────────────────
# Global Config
# ─────────────────────────────────────────────
BASE_URL = frappe.utils.get_url()
ALLOWED_ROLES = ["Merigate Entry User", "System Manager"]


# ─────────────────────────────────────────────
# Helper: Role Check
# ─────────────────────────────────────────────
def has_merigate_access(user_email):
    roles = frappe.get_roles(user_email)
    return any(role in roles for role in ALLOWED_ROLES)


# ─────────────────────────────────────────────
# 1. Login
# ─────────────────────────────────────────────
@frappe.whitelist(allow_guest=True)
def login_user(usr, pwd):
    """
    Step 1: Generate SID Token (Login API)
    Authenticates a user and generates a Session ID (SID).
    """
    try:
        # Input validation
        if not usr or not pwd:
            return {"status": "error", "message": "usr and pwd are required."}

        # User existence check
        if not frappe.db.exists("User", usr):
            return {"status": "error", "message": "User not found. Contact admin."}

        # Authenticate
        from frappe.auth import LoginManager
        try:
            lm = LoginManager()
            lm.authenticate(user=usr, pwd=pwd)
            lm.post_login()
            frappe.db.commit()
        except Exception:
            return {"status": "error", "message": "Invalid credentials."}

        # Role check after login
        if not has_merigate_access(usr):
            frappe.local.login_manager.logout()
            frappe.db.commit()
            return {"status": "error", "message": "Access not assigned. Contact admin."}

        # Return response matching the reference documentation structure
        return {
            "message": "Login successful",
            "sid": frappe.session.sid, # Return the generated session token
            "home_page": "/app/home",
            "full_name": frappe.db.get_value("User", usr, "full_name")
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "login_user Error")
        return {"status": "error", "message": str(e)}


# ─────────────────────────────────────────────
# 2. Create / Update Merigate Entry
# ─────────────────────────────────────────────
@frappe.whitelist(allow_guest=False)
def create_merigate_entry(**kwargs):
    """
    Step 2: Create Merigate Entry
    Expects multipart/form-data payload and a valid session cookie (sid).
    Uploads invoice details along with a PDF document and creates a Merigate request.
    """
    from frappe.utils.file_manager import save_file
    import json

    SKIP_FIELDS = {"name", "doctype", "owner", "creation", "modified", "cmd", "file"}

    # Session check is handled automatically by frappe when allow_guest=False
    # but we double-check just in case.
    if frappe.session.user == "Guest":
        return {"status": "error", "message": "Not logged in. Please provide valid SID."}

    # Role check
    if not has_merigate_access(frappe.session.user):
        return {"status": "error", "message": "Access denied. Contact admin."}

    try:
        # Create a new document (since docname is typically generated by naming series)
        doc = frappe.new_doc("Merigate Entry")

        # Map provided form fields to the document
        for key, value in kwargs.items():
            if key not in SKIP_FIELDS and hasattr(doc, key):
                setattr(doc, key, value)

        # Set default values if they aren't provided
        if not doc.get("category"):
            doc.category = "General Purchase"

        if not doc.get("status"):
            doc.status = "Open"

        # Insert document first to get the auto-generated docname
        doc.insert(ignore_permissions=True)

        file_url = None
        # Handle File Upload if a file is present in the request
        if getattr(frappe.request, "files", None) and "file" in frappe.request.files:
            uploaded_file = frappe.request.files["file"]
            
            # Read file content
            file_content = uploaded_file.read()
            file_name = uploaded_file.filename

            # Save file and attach it to the created Merigate Entry document
            saved_file = save_file(
                fname=file_name,
                content=file_content,
                dt="Merigate Entry",
                dn=doc.name,
                folder="Home/Attachments",
                is_private=1 # Can be 0 if you want public files
            )
            file_url = saved_file.file_url

        frappe.db.commit()

        # Return response matching the reference documentation structure
        return {
            "status": "success",
            "docname": doc.name,
            "file_url": file_url
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "create_merigate_entry Error")
        return {"status": "error", "message": str(e)}


# ─────────────────────────────────────────────
# 3. Logout
# ─────────────────────────────────────────────
@frappe.whitelist(allow_guest=True)
def logout_user():
    try:
        # Check if session is already expired
        if frappe.session.user == "Guest":
            return {"status": "error", "message": "No active session to logout."}

        frappe.local.login_manager.logout()
        frappe.db.commit()
        return {"status": "success", "message": "Logged out successfully."}

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "logout_user Error")
        return {"status": "error", "message": "Logout failed. Session may already be expired."}